name: Android Build

on: pull_request

jobs:
  build:

    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up  JDK
      uses: actions/setup-java@v2
      with:
        java-version:'11'

        - name: permission for gradlew
          run: chmod +x gradlew
        - name: Run test
          run: ./gradlew test
        - name: build project
          run: ./gradlew assemble
